### ISSUE TITLE
Make actionCreator's `type` public

### ISSUE THREAD

**Issue by tsugitta** [mizchi/hard-reducer#2]
First of all, thanks for an awesome library. This is so helpful to work with.

This might just be my idea but I want to get the action type of an actionCreator (which is now defined as `_t`) to use in middleware (e.g. redux-saga). [typescript-fsa](https://github.com/aikoven/typescript-fsa) makes it public.
How about making it public for middleware?

**Comment by mizchi** [comment]
Thank you for using!

IMO: Action's name is just for debugging message and catching signal in switch case. In addition, I add `prefix` option to build actionCreator context. It broke type inference. (and flowtype is very weak to detect string type to other files)

But anyway we may need escape hatch. `_t` 's naming means private value. I will expose it as `type: string`.

**Comment by mizchi** [comment]
Sorry to late. Please use `v2.1.0`!
